title: Manish Sharma
logo: /assets/img/ms-logo.jpg
description: Senior AI Engineer                  | Sr. Associate-Analytics NASSCOM Gold Certification | Turning Data into Intelligent Solutions.
#show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
