title: Manish Sharma
logo: /assets/img/ms-logo.jpg
description: Sr. Associate-Analytics NASSCOM Gold Certification | Aspiring Data Scientist | Turning Data into Intelligent Solutions.
#show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
